---

- hosts: webservers
  vars:
    - project_dir: /project
    - env_file_path: "{{ project_dir }}/.env"

  tasks:
    - ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - ansible.builtin.template:
        src: env.j2
        dest: "{{ env_file_path }}"
    
    - community.docker.docker_container:
        name: redmine
        image: redmine:5
        restart_policy: always
        state: started
        ports:
          - 80:3000
        env_file: "{{ env_file_path }}"

