---

- name: Redmine Playbook
  hosts: webservers
  vars:
    - project_dir: /project
    - env_file_path: "{{ project_dir }}/.env"

  tasks:
    - name: Project Directory
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Creating environment
      ansible.builtin.template:
        src: env.j2
        dest: "{{ env_file_path }}"
        mode: '0600'

    - name: Redmine
      community.docker.docker_container:
        name: redmine
        image: redmine:5
        restart_policy: always
        state: started
        ports:
          - 80:3000
        env_file: "{{ env_file_path }}"

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
